[tool.poetry]
name = "360-vvc"
version = "0.1.0"
description = ""
authors = ["0had0 <hadihoussainy75@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
